name:                audit
version:             0.1.0.0
github:              "githubuser/audit"
license:             BSD3
author:              "Jordan Millar"
maintainer:          "jordan.millar@iohk.io"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/audit#readme>

dependencies:
- base >= 4.7 && < 5
- beam-core
- beam-sqlite
- containers
- directory
- hashable
- hedgehog
- mtl
- optparse-applicative
- parsec
- process
- sqlite-simple
- text
- time

library:
  source-dirs: src
  exposed-modules:
  - Audit.Database
  - Audit.Generate
  - Audit.Parser
  - Audit.Sorting
  - Audit.Tree
  - Audit.Types
  ghc-options: -Wall

executables:
  audit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - audit

tests:
  audit-test:
    main:                test.hs
    source-dirs:         test
    other-modules:
    - Test.Audit.DepTree
    - Test.Audit.Gen
    - Test.Audit.TempDatabase
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - audit
